//! TLS-wrapped proxy listener (issue #110).
//!
//! Acceptance tests for the credential-onboarding milestone's transport
//! security feature: when the listener TLS acceptor is attached, the
//! proxy port requires a TLS handshake before any proxy protocol —
//! CONNECT (and `Proxy-Authorization` with it) happens inside the TLS
//! tunnel, a plaintext CONNECT to the same port is refused without any
//! HTTP response, and the engine keeps its plaintext behavior
//! byte-identical when the option is unset.
//!
//! The listener certificate under test is a real leaf generated by the
//! engine's own `CertificateManager` for `localhost`, so the test client
//! performs FULL rustls verification (CA trust + server name) — no
//! verification bypasses.

use std::sync::Arc;
use std::time::Duration;

use async_trait::async_trait;
use madhyamas_core::tls::load_listener_tls_acceptor;
use madhyamas_core::{
    CertificateManager, ProxyAuthValidator, ProxyConfig, ProxyCredentials, ProxyEngine,
    ProxyPrincipal, TrafficStore, TrafficStoreBackend,
};
use madhyamas_test_utils::spawn_mock_server;
use parking_lot::RwLock;

/// Validator that rejects every supplied credential (strict-auth tests).
struct RejectingValidator;

#[async_trait]
impl ProxyAuthValidator for RejectingValidator {
    async fn validate(&self, _credentials: &ProxyCredentials) -> Result<ProxyPrincipal, String> {
        Err("test: all credentials rejected".to_string())
    }
}

/// Pick a free TCP port by binding to :0 and immediately releasing it.
fn free_port() -> u16 {
    std::net::TcpListener::bind("127.0.0.1:0")
        .expect("bind :0 for port discovery")
        .local_addr()
        .expect("local addr")
        .port()
}

/// Wait until the proxy listener accepts TCP connections. The probe
/// connection carries no TLS and closes immediately — the engine's TLS
/// acceptor fails it at debug level, which is the behavior under test
/// anyway.
async fn wait_for_listener(addr: &str) {
    for _ in 0..100 {
        if tokio::net::TcpStream::connect(addr).await.is_ok() {
            return;
        }
        tokio::time::sleep(Duration::from_millis(25)).await;
    }
    panic!("proxy listener at {addr} never came up");
}

/// Generate a real listener identity: a leaf certificate for `localhost`
/// signed by a fresh `CertificateManager` CA, written as PEM files.
/// Returns (cert_path, key_path, ca_pem) — the CA PEM lets test clients
/// verify the listener with full rustls validation.
async fn listener_identity(
    dir: &tempfile::TempDir,
) -> (std::path::PathBuf, std::path::PathBuf, Vec<u8>) {
    let cert_manager =
        CertificateManager::new(dir.path().join("ca.pem").to_str().expect("utf8 path"))
            .await
            .expect("certificate manager");
    let leaf = cert_manager
        .generate_cert_for_host("localhost")
        .expect("leaf for localhost");
    let cert_path = dir.path().join("listener-cert.pem");
    let key_path = dir.path().join("listener-key.pem");
    std::fs::write(&cert_path, &leaf.certificate).expect("write cert pem");
    std::fs::write(&key_path, &leaf.private_key).expect("write key pem");
    (
        cert_path,
        key_path,
        cert_manager.ca_certificate_pem().to_vec(),
    )
}

/// A rustls client config that trusts the test CA (full verification —
/// the listener cert carries SAN DNS:localhost).
fn client_config(ca_pem: &[u8]) -> Arc<rustls::ClientConfig> {
    let mut roots = rustls::RootCertStore::empty();
    let certs = rustls_pemfile::certs(&mut std::io::Cursor::new(ca_pem))
        .collect::<Result<Vec<_>, _>>()
        .expect("parse CA pem");
    assert!(!certs.is_empty(), "test CA pem must contain a certificate");
    for cert in certs {
        roots.add(cert).expect("trust test CA");
    }
    // Explicit provider: under cargo-nextest each test is its own process,
    // so this helper must not rely on another test's install_default().
    Arc::new(
        rustls::ClientConfig::builder_with_provider(Arc::new(
            rustls::crypto::ring::default_provider(),
        ))
        .with_safe_default_protocol_versions()
        .expect("ring provider")
        .with_root_certificates(roots)
        .with_no_client_auth(),
    )
}

/// Build a started engine on an ephemeral port. `acceptor` is attached
/// when `Some`, reproducing the binary's startup wiring.
async fn started_engine(
    acceptor: Option<Arc<tokio_rustls::TlsAcceptor>>,
    validator: Option<Arc<dyn ProxyAuthValidator>>,
) -> (String, Arc<TrafficStore>) {
    let _ = rustls::crypto::ring::default_provider().install_default();

    let store = TrafficStore::in_memory().await.expect("in-memory store");
    let cert_dir = tempfile::TempDir::new().expect("temp dir for MITM certs");
    let cert_manager =
        CertificateManager::new(cert_dir.path().join("ca.pem").to_str().expect("utf8 path"))
            .await
            .expect("certificate manager");

    let port = free_port();
    let proxy_addr = format!("127.0.0.1:{port}");
    let config = ProxyConfig {
        host: "127.0.0.1".to_string(),
        proxy_port: port,
        ..Default::default()
    };

    let mut engine = ProxyEngine::new(
        Arc::new(RwLock::new(config)),
        cert_manager,
        store.clone() as Arc<dyn TrafficStoreBackend + Send + Sync>,
    )
    .await
    .expect("engine");
    if let Some(acceptor) = acceptor {
        engine = engine.with_proxy_tls_acceptor(acceptor);
    }
    if let Some(validator) = validator {
        engine = engine.with_proxy_auth_validator(validator);
    }
    tokio::spawn(async move {
        let _ = engine.start().await;
    });
    wait_for_listener(&proxy_addr).await;
    (proxy_addr, store)
}

/// TLS-connect to the listener as a verified client and hand the session
/// to the caller.
async fn tls_connect(
    proxy_addr: &str,
    ca_pem: &[u8],
) -> tokio_rustls::client::TlsStream<tokio::net::TcpStream> {
    let tcp = tokio::net::TcpStream::connect(proxy_addr)
        .await
        .expect("tcp connect to proxy");
    let connector = tokio_rustls::TlsConnector::from(client_config(ca_pem));
    let server_name = rustls::pki_types::ServerName::try_from("localhost".to_string())
        .expect("server name localhost");
    connector
        .connect(server_name, tcp)
        .await
        .expect("TLS handshake with proxy listener")
}

/// Read from a stream until the HTTP header terminator (bounded — never
/// deadlock the test on a peer that stays silent).
async fn read_http_head<S: tokio::io::AsyncRead + Unpin>(stream: &mut S) -> Vec<u8> {
    let mut out = Vec::new();
    tokio::time::timeout(Duration::from_secs(5), async {
        use tokio::io::AsyncReadExt;
        let mut buf = [0u8; 512];
        loop {
            let n = stream.read(&mut buf).await.expect("read");
            if n == 0 {
                break;
            }
            out.extend_from_slice(&buf[..n]);
            if out.ends_with(b"\r\n\r\n") || out.starts_with(b"HTTP/1.1 407") {
                break;
            }
        }
    })
    .await
    .expect("bounded read");
    out
}

// ─────────────────────────────────────────────────────────────────────────
// Acceptor loader (tls::load_listener_tls_acceptor)
// ─────────────────────────────────────────────────────────────────────────

#[tokio::test]
async fn load_listener_tls_acceptor_loads_generated_leaf() {
    let dir = tempfile::TempDir::new().expect("temp dir");
    let (cert_path, key_path, _ca) = listener_identity(&dir).await;
    let acceptor =
        load_listener_tls_acceptor(&cert_path, &key_path).expect("acceptor from valid PEM files");
    // The config advertised no ALPN protocols (CONNECT-over-TLS is
    // HTTP/1.1 framing; h2 is never offered on the listener).
    assert!(
        acceptor.config().alpn_protocols.is_empty(),
        "listener acceptor must not advertise ALPN"
    );
}

#[tokio::test]
async fn load_listener_tls_acceptor_missing_cert_file_names_path() {
    let dir = tempfile::TempDir::new().expect("temp dir");
    let (_cert_path, key_path, _ca) = listener_identity(&dir).await;
    let missing = dir.path().join("does-not-exist.pem");
    let err = load_listener_tls_acceptor(&missing, &key_path)
        .err()
        .expect("missing cert file must fail");
    let msg = format!("{}", err);
    assert!(
        msg.contains("does-not-exist.pem"),
        "error names the file: {msg}"
    );
}

#[tokio::test]
async fn load_listener_tls_acceptor_missing_key_file_names_path() {
    let dir = tempfile::TempDir::new().expect("temp dir");
    let (cert_path, _key_path, _ca) = listener_identity(&dir).await;
    let missing = dir.path().join("no-key.pem");
    let err = load_listener_tls_acceptor(&cert_path, &missing)
        .err()
        .expect("missing key file must fail");
    let msg = format!("{}", err);
    assert!(msg.contains("no-key.pem"), "error names the file: {msg}");
}

#[tokio::test]
async fn load_listener_tls_acceptor_garbage_cert_pem_names_path() {
    let dir = tempfile::TempDir::new().expect("temp dir");
    let (_cert_path, key_path, _ca) = listener_identity(&dir).await;
    let garbage = dir.path().join("garbage-cert.pem");
    std::fs::write(&garbage, b"not a pem at all").expect("write garbage");
    let err = load_listener_tls_acceptor(&garbage, &key_path)
        .err()
        .expect("garbage cert must fail");
    let msg = format!("{}", err);
    assert!(
        msg.contains("garbage-cert.pem"),
        "error names the file: {msg}"
    );
    // The error must not leak the file contents.
    assert!(
        !msg.contains("not a pem"),
        "error must not echo contents: {msg}"
    );
}

#[tokio::test]
async fn load_listener_tls_acceptor_garbage_key_pem_names_path() {
    let dir = tempfile::TempDir::new().expect("temp dir");
    let (cert_path, _key_path, _ca) = listener_identity(&dir).await;
    let garbage = dir.path().join("garbage-key.pem");
    std::fs::write(
        &garbage,
        b"-----BEGIN PRIVATE KEY-----\njunk\n-----END PRIVATE KEY-----\n",
    )
    .expect("write garbage key");
    let err = load_listener_tls_acceptor(&cert_path, &garbage)
        .err()
        .expect("unparseable key must fail");
    let msg = format!("{}", err);
    assert!(
        msg.contains("garbage-key.pem"),
        "error names the file: {msg}"
    );
}

#[tokio::test]
async fn load_listener_tls_acceptor_empty_cert_file_names_path() {
    let dir = tempfile::TempDir::new().expect("temp dir");
    let (_cert_path, key_path, _ca) = listener_identity(&dir).await;
    let empty = dir.path().join("empty-cert.pem");
    std::fs::write(&empty, b"").expect("write empty file");
    let err = load_listener_tls_acceptor(&empty, &key_path)
        .err()
        .expect("empty cert file must fail");
    let msg = format!("{}", err);
    assert!(
        msg.contains("empty-cert.pem"),
        "error names the file: {msg}"
    );
    assert!(msg.to_lowercase().contains("no certificates"), "{msg}");
}

/// A certificate paired with a DIFFERENT key fails fail-closed at build
/// time — rustls 0.23 validates key/cert consistency in
/// `with_single_cert`, so a botched deployment (right files, wrong pair)
/// aborts at startup instead of every handshake failing later. The error
/// names both file paths and leaks no key material.
#[tokio::test]
async fn load_listener_tls_acceptor_rejects_cert_key_mismatch() {
    let dir_a = tempfile::TempDir::new().expect("temp dir a");
    let dir_b = tempfile::TempDir::new().expect("temp dir b");
    let (cert_a, _key_a, _ca_a) = listener_identity(&dir_a).await;
    let (_cert_b, key_b, _ca_b) = listener_identity(&dir_b).await;
    let err = load_listener_tls_acceptor(&cert_a, &key_b)
        .err()
        .expect("mismatched cert/key must fail at build time");
    let msg = format!("{}", err);
    assert!(
        msg.contains("listener-cert.pem") && msg.contains("listener-key.pem"),
        "error names both files: {msg}"
    );
}

// ─────────────────────────────────────────────────────────────────────────
// Engine accept path over TLS (the issue's acceptance criteria)
// ─────────────────────────────────────────────────────────────────────────

/// Acceptance: a TLS-wrapped listener accepts CONNECT over TLS (verified
/// client, real engine accept loop) and answers 200 Connection
/// Established over the encrypted stream.
#[tokio::test]
async fn tls_listener_accepts_connect_over_tls() {
    let dir = tempfile::TempDir::new().expect("temp dir");
    let (cert_path, key_path, ca_pem) = listener_identity(&dir).await;
    let acceptor = load_listener_tls_acceptor(&cert_path, &key_path).expect("acceptor");
    let (proxy_addr, _store) = started_engine(Some(acceptor), None).await;

    let mut tls = tls_connect(&proxy_addr, &ca_pem).await;
    use tokio::io::AsyncWriteExt;
    tls.write_all(b"CONNECT localhost:443 HTTP/1.1\r\nHost: localhost:443\r\n\r\n")
        .await
        .expect("send CONNECT over TLS");
    let head = read_http_head(&mut tls).await;
    let text = String::from_utf8_lossy(&head);
    assert!(
        text.starts_with("HTTP/1.1 200"),
        "CONNECT over TLS must be established, got: {text}"
    );
    let _ = tls.shutdown().await;
}

/// Acceptance: a plaintext CONNECT sent to the TLS-wrapped port is
/// refused WITHOUT any HTTP response — the client sees only a TLS alert
/// (or a close), never a 200/407/404 that would disclose proxy behavior.
#[tokio::test]
async fn tls_listener_refuses_plaintext_connect_without_http_response() {
    let dir = tempfile::TempDir::new().expect("temp dir");
    let (cert_path, key_path, _ca_pem) = listener_identity(&dir).await;
    let acceptor = load_listener_tls_acceptor(&cert_path, &key_path).expect("acceptor");
    let (proxy_addr, _store) = started_engine(Some(acceptor), None).await;

    use tokio::io::{AsyncReadExt, AsyncWriteExt};
    let mut sock = tokio::net::TcpStream::connect(&proxy_addr)
        .await
        .expect("plaintext connect to TLS port");
    sock.write_all(b"CONNECT localhost:443 HTTP/1.1\r\nHost: localhost:443\r\n\r\n")
        .await
        .expect("send plaintext CONNECT");

    let mut buf = Vec::new();
    let _ = tokio::time::timeout(Duration::from_secs(3), async {
        let mut chunk = [0u8; 128];
        loop {
            let n = sock.read(&mut chunk).await.expect("read");
            if n == 0 {
                break;
            }
            buf.extend_from_slice(&chunk[..n]);
        }
    })
    .await;
    assert!(
        !buf.starts_with(b"HTTP/"),
        "plaintext CONNECT must not receive an HTTP response, got: {:?}",
        String::from_utf8_lossy(&buf)
    );
}

/// The proxy-auth gate works through the TLS listener: with strict auth
/// required and no credentials, the 407 is written to the ENCRYPTED
/// stream (the very property that motivates issue #110 — on the
/// plaintext listener this exchange is base64-cleartext).
#[tokio::test]
async fn tls_listener_sends_407_over_encrypted_stream() {
    let dir = tempfile::TempDir::new().expect("temp dir");
    let (cert_path, key_path, ca_pem) = listener_identity(&dir).await;
    let acceptor = load_listener_tls_acceptor(&cert_path, &key_path).expect("acceptor");
    let (proxy_addr, _store) =
        started_engine(Some(acceptor), Some(Arc::new(RejectingValidator))).await;

    let mut tls = tls_connect(&proxy_addr, &ca_pem).await;
    use tokio::io::AsyncWriteExt;
    // No Proxy-Authorization: engine default is strict (407 on missing).
    tls.write_all(b"CONNECT localhost:443 HTTP/1.1\r\nHost: localhost:443\r\n\r\n")
        .await
        .expect("send unauthenticated CONNECT over TLS");
    let head = read_http_head(&mut tls).await;
    let text = String::from_utf8_lossy(&head);
    assert!(
        text.starts_with("HTTP/1.1 407"),
        "strict auth must 407 over the TLS stream, got: {text}"
    );
    assert!(
        text.contains("proxy_auth_required"),
        "407 body shape preserved: {text}"
    );
}

/// Absolute-form HTTP proxying over the TLS listener: a plain GET with a
/// full URL travels through `handle_http_proxy` on the decrypted stream
/// and the upstream's 200 comes back over TLS.
#[tokio::test]
async fn tls_listener_proxies_absolute_form_http_over_tls() {
    let (upstream_url, _upstream_rx) = spawn_mock_server().await;
    let dir = tempfile::TempDir::new().expect("temp dir");
    let (cert_path, key_path, ca_pem) = listener_identity(&dir).await;
    let acceptor = load_listener_tls_acceptor(&cert_path, &key_path).expect("acceptor");
    let (proxy_addr, _store) = started_engine(Some(acceptor), None).await;

    let mut tls = tls_connect(&proxy_addr, &ca_pem).await;
    use tokio::io::AsyncWriteExt;
    let request = format!(
        "GET {upstream_url}/over-tls HTTP/1.1\r\nHost: 127.0.0.1\r\nConnection: close\r\n\r\n"
    );
    tls.write_all(request.as_bytes())
        .await
        .expect("send absolute-form GET over TLS");

    let mut head = Vec::new();
    tokio::time::timeout(Duration::from_secs(5), async {
        use tokio::io::AsyncReadExt;
        let mut buf = [0u8; 1024];
        loop {
            // The proxy closes the connection after the response without
            // a TLS close_notify (plain-socket semantics) — rustls
            // surfaces that as UnexpectedEof. The response bytes are
            // already delivered, so any EOF (clean or not) ends the read.
            match tls.read(&mut buf).await {
                Ok(0) | Err(_) => break,
                Ok(n) => {
                    head.extend_from_slice(&buf[..n]);
                    if head.ends_with(b"\r\n\r\n") || head.len() > 8192 {
                        break;
                    }
                }
            }
        }
    })
    .await
    .expect("bounded read");
    let text = String::from_utf8_lossy(&head);
    assert!(
        text.starts_with("HTTP/1.1 200"),
        "absolute-form GET must be proxied over TLS, got: {text}"
    );
}

/// Regression: without the acceptor attached (the default), the listener
/// stays plaintext — a plain CONNECT still gets its 200 byte-identically.
#[tokio::test]
async fn plain_listener_unchanged_without_acceptor() {
    let (proxy_addr, _store) = started_engine(None, None).await;

    use tokio::io::{AsyncReadExt, AsyncWriteExt};
    let mut sock = tokio::net::TcpStream::connect(&proxy_addr)
        .await
        .expect("connect plain listener");
    sock.write_all(b"CONNECT localhost:443 HTTP/1.1\r\nHost: localhost:443\r\n\r\n")
        .await
        .expect("send plain CONNECT");

    let mut out = Vec::new();
    tokio::time::timeout(Duration::from_secs(3), async {
        let mut buf = [0u8; 128];
        loop {
            let n = sock.read(&mut buf).await.expect("read");
            if n == 0 {
                break;
            }
            out.extend_from_slice(&buf[..n]);
            if out.ends_with(b"\r\n\r\n") {
                break;
            }
        }
    })
    .await
    .expect("bounded read");
    assert!(
        String::from_utf8_lossy(&out).starts_with("HTTP/1.1 200 Connection Established"),
        "plain listener must be unchanged, got: {}",
        String::from_utf8_lossy(&out)
    );
}
