//! TLS certificate management for HTTPS interception

mod certificate;

pub use certificate::CertificateManager;

use rustls::pki_types::{CertificateDer, PrivateKeyDer};

/// Generated certificate pair
#[derive(Clone)]
pub struct GeneratedCert {
    pub certificate: Vec<u8>,
    pub private_key: Vec<u8>,
}

impl GeneratedCert {
    /// Get certificate as DER
    pub fn cert_der(&self) -> CertificateDer<'_> {
        CertificateDer::from(self.certificate.clone())
    }

    /// Get private key as DER
    pub fn key_der(&self) -> PrivateKeyDer<'_> {
        PrivateKeyDer::try_from(self.private_key.clone())
            .unwrap_or_else(|_| PrivateKeyDer::Pkcs1(self.private_key.clone().into()))
    }
}

/// The CryptoProvider used for every rustls configuration Madhyamas
/// builds: MITM leaf certs, the TLS-wrapped proxy listener, and upstream
/// client connections.
///
/// Always explicit, never the ambient process-level provider:
/// workspace-wide feature unification can enable *both* `ring` and
/// `aws-lc-rs` in rustls, and rustls 0.23.45+ panics on ambiguous
/// auto-detection instead of silently picking one. Being explicit also
/// keeps `cargo-nextest` (one test per process) safe — no test depends
/// on another having called `CryptoProvider::install_default()` first.
fn ring_provider() -> std::sync::Arc<rustls::crypto::CryptoProvider> {
    std::sync::Arc::new(rustls::crypto::ring::default_provider())
}

/// Server-config builder pinned to [`ring_provider`] with safe default
/// protocol versions. Statically infallible for the ring provider, so
/// the init result is unwrapped.
pub(crate) fn ring_server_builder(
) -> rustls::ConfigBuilder<rustls::ServerConfig, rustls::WantsVerifier> {
    rustls::ServerConfig::builder_with_provider(ring_provider())
        .with_safe_default_protocol_versions()
        .expect("ring CryptoProvider with safe default protocol versions")
}

/// Client-config builder pinned to [`ring_provider`] with safe default
/// protocol versions.
pub(crate) fn ring_client_builder(
) -> rustls::ConfigBuilder<rustls::ClientConfig, rustls::WantsVerifier> {
    rustls::ClientConfig::builder_with_provider(ring_provider())
        .with_safe_default_protocol_versions()
        .expect("ring CryptoProvider with safe default protocol versions")
}

/// Build the TLS acceptor for the proxy listener itself (issue #110 —
/// transport TLS for the proxy port, distinct from the MITM interception
/// leaf certificates generated by [`CertificateManager`]).
///
/// Reads a PEM certificate chain and private key from disk and builds a
/// rustls server configuration with **no ALPN protocols advertised**:
/// clients speak HTTP/1.1 framing (`CONNECT` or absolute-form proxy
/// requests) inside the TLS tunnel, and the proxy does not support
/// HTTP/2 proxying, so advertising `h2` would only invite broken
/// negotiations.
///
/// The files are read exactly once (at startup); the acceptor produced
/// here is attached to the engine via
/// [`crate::proxy::ProxyEngine::with_proxy_tls_acceptor`] and wraps every
/// accepted socket before CONNECT parsing, so proxy credentials
/// (`Proxy-Authorization`) never cross the network in the clear.
///
/// Errors name the offending file's path (never its contents) so a
/// misconfigured deployment fails closed at startup with a clear message
/// instead of failing per-connection later.
pub fn load_listener_tls_acceptor(
    cert_path: &std::path::Path,
    key_path: &std::path::Path,
) -> crate::Result<std::sync::Arc<tokio_rustls::TlsAcceptor>> {
    let cert_pem = std::fs::read(cert_path).map_err(|e| {
        crate::Error::Tls(format!(
            "failed to read proxy listener TLS certificate file {}: {}",
            cert_path.display(),
            e
        ))
    })?;
    let key_pem = std::fs::read(key_path).map_err(|e| {
        crate::Error::Tls(format!(
            "failed to read proxy listener TLS key file {}: {}",
            key_path.display(),
            e
        ))
    })?;

    let cert_chain = rustls_pemfile::certs(&mut std::io::Cursor::new(&cert_pem))
        .collect::<Result<Vec<_>, _>>()
        .map_err(|e| {
            crate::Error::Tls(format!(
                "failed to parse certificates from {}: {}",
                cert_path.display(),
                e
            ))
        })?;
    if cert_chain.is_empty() {
        return Err(crate::Error::Tls(format!(
            "no certificates found in proxy listener TLS certificate file {}",
            cert_path.display()
        )));
    }

    let private_key = rustls_pemfile::private_key(&mut std::io::Cursor::new(&key_pem))
        .map_err(|e| {
            crate::Error::Tls(format!(
                "failed to parse private key from {}: {}",
                key_path.display(),
                e
            ))
        })?
        .ok_or_else(|| {
            crate::Error::Tls(format!(
                "no private key found in proxy listener TLS key file {}",
                key_path.display()
            ))
        })?;

    let config = ring_server_builder()
        .with_no_client_auth()
        .with_single_cert(cert_chain, private_key)
        .map_err(|e| {
            crate::Error::Tls(format!(
                "failed to build proxy listener TLS configuration from {} / {}: {}",
                cert_path.display(),
                key_path.display(),
                e
            ))
        })?;

    // No ALPN: HTTP/1.1 framing only inside the tunnel (see the doc
    // comment above). `alpn_protocols` stays empty.
    Ok(std::sync::Arc::new(tokio_rustls::TlsAcceptor::from(
        std::sync::Arc::new(config),
    )))
}
