[package]
name = "madhyamas-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "CLI tool for interacting with Madhyamas proxy server"
repository.workspace = true
authors.workspace = true

[lib]
name = "madhyamas_cli"
path = "src/lib.rs"

[[bin]]
name = "madhyamas-cli"
path = "src/main.rs"

[dependencies]
tokio.workspace = true
clap.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
reqwest.workspace = true
madhyamas-core = { path = "../madhyamas-core", version = "0.1.6", default-features = false, features = [
    "plugins",
] }

[dev-dependencies]
madhyamas-test-utils.workspace = true
